### ISSUE TITLE
feat: Support for custom registries

### ISSUE THREAD

**Issue by jordanbertasso** [danielhuang/cotton#108]
It would be nice if cotton could support fetching packages from an arbitrary url instead of only https://registry.npmjs.org/.

I see two things to implement here:
1. A global custom registry - https://docs.npmjs.com/cli/v7/using-npm/config#registry
2. Custom registry's for scoped packages - https://docs.npmjs.com/cli/v7/using-npm/scope#associating-a-scope-with-a-registry

**Comment by danielhuang** [comment]
Initial support has been implemented. To use custom registries, save them into `cotton.toml`. For example:

```toml
[[registry]]
scope = "@example/"
url = "https://registry.example.com"
auth = { token = "insert_token_here" }

[[registry]]
scope = "@example2/"
url = "https://registry2.example.com"
auth = { from_env = "TOKEN" }

[[registry]]
url = "https://default-registry.example.com"
auth = { from_env = "TOKEN2" }
```

More specific registries (such as those with scopes) should be placed first, as priority is considered in order.

**Comment by jordanbertasso** [comment]
This is awesome work!

Although unfortunately I'm still unable to use cotton for my use case because the registry I need to authenticate to requires that I do it using a username and password ([defined here](https://docs.npmjs.com/cli/v9/configuring-npm/npmrc#auth-related-configuration)) instead of a token.

**Comment by danielhuang** [comment]
Registries can now be used with usernames and passwords:

```toml
[[registry]]
url = "https://registry.npmjs.org"
auth = { username = "user", password = "password" }
```

It can also come from the environment:

```toml
[[registry]]
url = "https://registry.npmjs.org"
auth = { username = { from_env = "USERNAME" }, password = { from_env = "PASSWORD" } }
```
